version: "3.8"
services:
  qies:
    image: ghcr.io/omriharary/qies/web:1.1.0-beta
    build:
      context: ./QIES/
      secrets:
      - nuget
    ports:
    - "5000:80"
    volumes:
    - "service_files:/var/opt:ro"
    - "summary_files:/var/tmp"
    depends_on:
    - backoffice

  backoffice:
    image: ghcr.io/omriharary/qies/backoffice:2.0.3
    build:
      context: ./QIES.Backoffice/
      secrets:
      - nuget
    volumes:
    - "service_files:/var/opt"
    - "summary_files:/var/tmp"

volumes:
  service_files: {}
  summary_files: {}

secrets:
  nuget:
    file: ~/.nuget/NuGet/NuGet.Config
