#!/bin/bash

for i in $( ls ./QIES.Frontend/test/cases )
do
    for j in $( ls "./QIES.Frontend/test/cases/$i" )
    do
        rm -f "./QIES.Frontend/test/cases/$i/$j/output.txt"
        rm -f "./QIES.Frontend/test/cases/$i/$j/log.log"
    done
done
